name: CI
# This workflow is triggered on pushes to the repository.
on: [push, pull_request]

jobs:
  build-test:
    name: Test
    runs-on: ubuntu-latest
    container: ghcr.io/packagrio/packagr:latest-golang
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        env:
          GOOS: linux
          GOARCH: amd64
        run: |
          go mod vendor
          go test -mod vendor -race ./...
